[package]
name = "wrief"
version = "0.1.0"
edition = "2021"
description = "A HTTP server that can be used for Python."
license = "MIT License"
homepage = "https://github.com/Jkrox/Wrief"

[dependencies]
